services:
  mysql:
    image: mysql:8.0
    container_name: arsenal_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: arsenal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./inits:/docker-entrypoint-initdb.d
      - arsenal_mysql_data:/var/lib/mysql

volumes:
  arsenal_mysql_data: